import "./globals.css";

import { ReactNode } from "react";
import type { Metadata } from "next";
import { Poppins, Plus_Jakarta_Sans } from "next/font/google";

const poppins = Poppins({ variable: "--font-poppins", subsets: ["latin"], weight: "300" });
const jakarta = Plus_Jakarta_Sans({ variable: "--font-jakarta", subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" className={`${poppins.variable} ${jakarta.variable} h-full antialiased`}>
            <body className="dark flex min-h-full flex-col">{children}</body>
        </html>
    );
}
