import "./globals.css";

import { Toaster } from "sonner";
import type { Metadata } from "next";
// import { ClerkProvider } from "@clerk/nextjs";
import type { CSSProperties, ReactNode } from "react";
import AuthWrapper from "@/components/auth/auth-wrapper";

export const metadata: Metadata = {
    title: "Whisper",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    const fontVars = {
        "--font-poppins": '"Manrope", "Segoe UI", sans-serif',
        "--font-jakarta": '"Sora", "Avenir Next", "Segoe UI", sans-serif',
    } as CSSProperties;

    return (
        <html lang="en" className="h-full antialiased" style={fontVars}>
            <body className="dark flex min-h-full flex-col">
                {/* <ClerkProvider> */}
                <AuthWrapper>{children}</AuthWrapper>
                <Toaster position="top-center" />
                {/* </ClerkProvider> */}
            </body>
        </html>
    );
}
