import "./globals.css";

import { Toaster } from "sonner";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import type { CSSProperties, ReactNode } from "react";
import AuthWrapper from "@/components/auth/auth-wrapper";
import { Poppins, Plus_Jakarta_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

export const metadata: Metadata = { title: "Whisper", description: "Generated by create next app" };

const poppins = Poppins({ variable: "--font-poppins", weight: [ "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"] });
const jakarta = Plus_Jakarta_Sans({ variable: "--font-jakarta", weight: ["200", "300", "400", "500", "600", "700", "800"], subsets: ["latin"] });

const fontVars = {
    "--font-poppins": '"Manrope", "Segoe UI", sans-serif',
    "--font-jakarta": '"Sora", "Avenir Next", "Segoe UI", sans-serif',
} as CSSProperties;

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" className={cn(poppins.variable, jakarta.variable, fontVars, "antialiased")}>
            <body className="dark flex min-h-full flex-col">
                <ClerkProvider>
                    <AuthWrapper>{children}</AuthWrapper>
                    <Toaster position="top-center" />
                </ClerkProvider>
            </body>
        </html>
    );
}
